# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders/order_approved/v1/order_approved.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-orders/order_approved/v1/order_approved.proto\x12\x18orders.order_approved.v1\"\xac\x01\n\rOrderApproved\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\x12%\n\x0e\x63orrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x19\n\x08order_id\x18\x03 \x01(\tR\x07orderId\x12\x1f\n\x0b\x63ustomer_id\x18\x04 \x01(\tR\ncustomerId\x12\x1d\n\ncreated_at\x18\x05 \x01(\tR\tcreatedAtb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders.order_approved.v1.order_approved_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERAPPROVED._serialized_start=76
  _ORDERAPPROVED._serialized_end=248
# @@protoc_insertion_point(module_scope)
